import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import 'bootstrap/dist/css/bootstrap.css'
import React, {useState} from "react";
import {NextRouter, useRouter} from 'next/router';
import cookie from 'js-cookie';
import {Grade} from "./@me";


const authToken = cookie.get("auth")

function logOut(router: NextRouter) {
  cookie.set("auth", "")
  router.push("http://localhost:3000")
}
export function getUserAsync(setUser: (user: User|null) => void) {
  React.useEffect(() => {
    fetch("http://localhost:7000/api/user/@me", {
      headers: [ ["auth", authToken ?? "" ] ]
    })
        .then(x => x.json())
        .then(x => x as User)
        .catch(e => {console.log(e); return null})
        .then(e => setUser(e))
  }, [])

}
export function Header(props: { user: User | null, router: NextRouter}) {
  return <div style={{
    display: "flex",
    flexDirection: "row",
    padding: "15px",
    width: "100%",
    // height: "75px",
    backgroundColor: "white",
    borderBottom: "black 1px solid"
  }}>
    <button className={styles.headerbox + " btn btn-primary"} onClick={() => props.router.push("http://localhost:3000/home")}>Home</button>
    <a className={styles.headerbox + " btn btn-outline-primary"} style={{marginLeft: "auto"}} href={"http://localhost:3000/@me"}>{props.user?.username}#{props.user?.discrim}</a>
    <button className={styles.headerbox + " btn btn-outline-primary"} onClick={() => logOut(props.router)}>Log Out</button>
  </div>
}
function PeopleList() {
  const [people, setPeople] = useState<User[]|null>(null)
  React.useEffect(() => {
    fetch("http://localhost:7000/api/users")
        .then(x => x.json())
        .then(x => setPeople(x as User[]))
  }, [])
  if(people == null) return <></>
  return <div>
    {people.map(({ username, discrim, grade }) =>
        <div key={discrim}><span>{username}#{discrim}</span><span>{grade}</span></div>
    )}
  </div>
}


export default function Home() {

  const [user, setUser] = useState<User | null>(null)
  getUserAsync(setUser)



  const router = useRouter()
    return (
        <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Header user={user} router={router}/>

      <PeopleList/>



      <main className={styles.main}>


        <h1 className={styles.title}>
          Welcome, {user?.username ?? ""}#{user?.discrim ?? ""}
        </h1>
        <div style={{ display: "flex", flexDirection: "row"}}>

      </div>
      </main>


    </div>
  )
}

export type User = { username: string, id: string, discrim: string, classes: Class[], grade: Grade}
export type Class = { name: string, teacher: string }