import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import 'bootstrap/dist/css/bootstrap.css'
import React, {useState} from "react";


export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Oakton Classes 2021 Website
                </h1>

                <SignInButton/>
                <a className={"btn btn-primary"} style={{margin: "12px"}} href={"http://localhost:3000/home"}>
                    Home
                </a>
            </main>

        </div>
    );
}
export function SignInButton(): JSX.Element {

    return <a
        className={"btn btn-outline-primary"} style={{ margin: "12px"}}
        href={discordURL}>
        Log In
    </a>
}

const discordURL = "https://discord.com/api/oauth2/authorize?client_id=747884756011712705&redirect_uri=http%3A%2F%2Flocalhost%3A7000%2Fapi%2Foauth%2Fredirect&response_type=code&scope=identify"

function CounterButton() {
    const [n, setN] = useState(0)
    // let sse: EventSource;
    React.useEffect(() => {
        const sse = new EventSource("http://localhost:7000/sse")
        sse.onerror = (e) => { console.log(e); sse.close() }
        sse.addEventListener("update", (e ) => {
            console.log(e)
            setN((e as any).data)
        })
        sse.onopen = (e) => {console.log(e)}
    }, [])


    return <button
            type={"button"}
            className={"btn btn-outline-primary"}
            style={{ margin: "12px" }}
            onClick={() => fetch("http://localhost:7000/incr", {method: 'POST'})}>

            This button has been clicked {n} times
        </button>
}
